# Site settings
title: myblog
description: lyp'blog
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: lynn
user_description: I'm a lynn.
user_title: 菜鸡
email: 2371119495@qq.com
# twitter_username: non
instagram_username: non
facebook_username: non
linkedin_username: non
github_username:  ursa-ping
# medium_username: lynn
# medium_url: non
# gplus_username:  non

exclude: ['package.json', 'src' , 'node_modules']
